# Generated by Django 3.2.6 on 2021-09-21 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210825_2155'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='password_auth_token',
            field=models.CharField(default='12345', max_length=100),
        ),
    ]
