# Generated by Django 3.2.6 on 2021-08-26 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('diseases', '0002_alter_disease_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disease',
            name='description',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
